**Задание на повторение материала**

1. Создать одномерный массив Numpy под названием a из 12 последовательных целых чисел чисел от 12 до 24 невключительно

In [1]:
import numpy as np

In [2]:
a = np.arange(12,24)
a.shape

(12,)

2. Создать 5 двумерных массивов разной формы из массива a. Не использовать в аргументах метода reshape число -1.

In [3]:
a1 = a.reshape((12,1))
a2 = a.reshape((2,6))
a3 = a.reshape((3,4))
a4 = a.reshape((4,3))
a5 = a.reshape((6,2))

print(f'1: {a1} \n \n2: {a2}  \n \n3: {a3}  \n \n4: {a4}  \n \n5: {a5}  \n')

1: [[12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]] 
 
2: [[12 13 14 15 16 17]
 [18 19 20 21 22 23]]  
 
3: [[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]  
 
4: [[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]  
 
5: [[12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]]  



3. Создать 5 двумерных массивов разной формы из массива a. Использовать в аргументах метода reshape число -1 (в трех примерах - для обозначения числа столбцов, в двух - для строк).

In [4]:
a1 = a.reshape((-1,12))
a2 = a.reshape((-1,6))
a3 = a.reshape((-1,4))
a4 = a.reshape((4,-1))
a5 = a.reshape((6,-1))

print(f'1: {a1} \n \n2: {a2}  \n \n3: {a3}  \n \n4: {a4}  \n \n5: {a5}  \n')

1: [[12 13 14 15 16 17 18 19 20 21 22 23]] 
 
2: [[12 13 14 15 16 17]
 [18 19 20 21 22 23]]  
 
3: [[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]  
 
4: [[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]  
 
5: [[12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]]  



4. Можно ли массив Numpy, состоящий из одного столбца и 12 строк, назвать одномерным?

Ответ: Нет, это отражают квадратные скобки, применимые в выводе массива. Сравним изначальный массив а и его решейп:

In [5]:
print(f'а: {a} \n \nрешейп: {a.reshape(12,1)}')

а: [12 13 14 15 16 17 18 19 20 21 22 23] 
 
решейп: [[12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]]


5. Создать массив из 3 строк и 4 столбцов, состоящий из случайных чисел с плавающей запятой из нормального распределения со средним, равным 0 и среднеквадратичным отклонением, равным 1.0. Получить из этого массива одномерный массив с таким же атрибутом size, как и исходный массив.

In [6]:
b=np.random.randn(3,4)
b

array([[-0.24077445,  1.08693056, -0.08646473,  0.03105413],
       [ 0.02332538,  0.98616701,  0.40068547,  0.94846351],
       [ 0.42731703,  1.53648519,  0.25332188, -0.21237579]])

In [7]:
b.flatten()

array([-0.24077445,  1.08693056, -0.08646473,  0.03105413,  0.02332538,
        0.98616701,  0.40068547,  0.94846351,  0.42731703,  1.53648519,
        0.25332188, -0.21237579])

6. Создать массив a, состоящий из целых чисел, убывающих от 20 до 0 невключительно с интервалом 2.

In [9]:
a = np.arange(20,0,-2)
a

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

7. Создать массив b, состоящий из 1 строки и 10 столбцов: целых чисел, убывающих от 20 до 1 невключительно с интервалом 2. В чем разница между массивами a и b?

In [10]:
b = np.arange(20,0,-2).reshape(1,-1)
b

array([[20, 18, 16, 14, 12, 10,  8,  6,  4,  2]])

In [11]:
#отличие массива а от b заключается в том, что а - одномерный, а b -- двумерный

8. Вертикально соединить массивы a и b. a - двумерный массив из нулей, число строк которого больше 1 и на 1 меньше, чем число строк двумерного массива b, состоящего из единиц. Итоговый массив v должен иметь атрибут size, равный 10.

In [12]:
a = np.zeros((2, 2))
b = np.zeros((3, 2))+1
sum = np.vstack((a, b))
sum

array([[0., 0.],
       [0., 0.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [13]:
sum.size

10

9. Создать одномерный массив а, состоящий из последовательности целых чисел от 0 до 12. Поменять форму этого массива, чтобы получилась матрица A (двумерный массив Numpy), состоящая из 4 строк и 3 столбцов. Получить матрицу At путем транспонирования матрицы A. Получить матрицу B, умножив матрицу A на матрицу At с помощью матричного умножения. Какой размер имеет матрица B? Получится ли вычислить обратную матрицу для матрицы B и почему?

In [18]:
a = np.arange(0,12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [19]:
A = a.reshape(4,3)
A

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [21]:
At = A.T
At

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

In [22]:
B = np.dot(A,At)
B

array([[  5,  14,  23,  32],
       [ 14,  50,  86, 122],
       [ 23,  86, 149, 212],
       [ 32, 122, 212, 302]])

In [23]:
B.size

16

In [24]:
B.shape

(4, 4)

In [25]:
np.linalg.inv(B)

LinAlgError: Singular matrix

Ответ: несмотря на то, что полученная матрица В является квадратной, невозможно вычислить ее обратную матрицу, тк она является сингулярной, т.е. квадратная матрица. определитель которой. равен нулю.

10. Инициализируйте генератор случайных числе с помощью объекта seed, равного 42.

In [41]:
np.random.seed(42)

11. Создайте одномерный массив c, составленный из последовательности 16-ти случайных равномерно распределенных целых чисел от 0 до 16 невключительно. 


In [60]:
a = np.random.randint(0,16,16)
a

array([13, 13, 14, 13,  2, 11,  6,  3, 15,  8,  2,  4,  2,  6,  4,  8])

12. Поменяйте его форму так, чтобы получилась квадратная матрица C. Получите матрицу D, поэлементно прибавив матрицу B из предыдущего вопроса к матрице C, умноженной на 10. Вычислите определитель, ранг и обратную матрицу D_inv для D.


In [61]:
C = a.reshape(4,4)
C

array([[13, 13, 14, 13],
       [ 2, 11,  6,  3],
       [15,  8,  2,  4],
       [ 2,  6,  4,  8]])

In [62]:
D = B + C*10
D

array([[135, 144, 163, 162],
       [ 34, 160, 146, 152],
       [173, 166, 169, 252],
       [ 52, 182, 252, 382]])

In [63]:
np.linalg.det(D)

-166614399.99999964

In [64]:
np.linalg.matrix_rank(D)

4

In [66]:
D_inv = np.linalg.inv(D)

13. Приравняйте к нулю отрицательные числа в матрице D_inv, а положительные - к единице. Убедитесь, что в матрице D_inv остались только нули и единицы. С помощью функции numpy.where, используя матрицу D_inv в качестве маски, а матрицы B и C - в качестве источников данных, получите матрицу E размером 4x4.  Элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 1, должны быть равны соответствующему элементу матрицы B, а элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 0, должны быть равны соответствующему элементу матрицы C.

In [67]:
D_inv=np.where(D_inv<0, 0,1)
D_inv

array([[1, 0, 1, 0],
       [0, 1, 1, 0],
       [1, 0, 0, 1],
       [0, 0, 1, 1]])

In [68]:
E=np.where(D_inv==1, B, C)
E

array([[  5,  13,  23,  13],
       [  2,  50,  86,   3],
       [ 23,   8,   2, 212],
       [  2,   6, 212, 302]])